export default {
  pluginId: 'iximei/crm',
  name: 'crm',
  menuRootEnabled: false,
  version: '1.0.0',
  coreCompatibility: '^1.0.0',
  channels: ['admin', 'public'],
  routeBase: '/api/modules/crm/v1',
  icon: 'customer-service',
  permissions: [
    'crm:hospital:list',
    'crm:hospital:create',
    'crm:hospital:update',
    'crm:hospital:delete',
    'crm:customer:list',
    'crm:customer:create',
    'crm:customer:update',
    'crm:customer:dispatch',
    'crm:member:list',
    'crm:member:create',
    'crm:member:update',
    'crm:member:remark',
    'crm:dispatch:list',
    'crm:dispatch:update',
    'crm:dispatch:reply',
    'crm:dispatch:log',
    'crm:dispatch:export',
  ],
  menus: [
    { channel: 'admin', path: '/plugins/iximei/crm/hospitals', name: '医院管理', perm: 'crm:hospital:list', icon: 'bank' },
    { channel: 'admin', path: '/plugins/iximei/crm/customers', name: '客户管理', perm: 'crm:customer:list', icon: 'user' },
    { channel: 'admin', path: '/plugins/iximei/crm/members', name: '会员顾客', perm: 'crm:member:list', icon: 'crown' },
    { channel: 'admin', path: '/plugins/iximei/crm/dispatches', name: '派单管理', perm: 'crm:dispatch:list', icon: 'send' },
  ],
} as const;
