import { datetime, date, int, json, mysqlTable, text, varchar, uniqueIndex, index } from 'drizzle-orm/mysql-core'
import { sql } from 'drizzle-orm'

const timestamps = {
  createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`),
  updatedAt: datetime('updated_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`),
}

export const crmHospital = mysqlTable('crm_hospital', {
  id: int().primaryKey().autoincrement().notNull(), accountUserId: int('account_user_id'), hospitalName: varchar('hospital_name', { length: 100 }).notNull(), provinceId: int('province_id'), cityId: int('city_id'), districtId: int('district_id'), hospitalAddress: varchar('hospital_address', { length: 255 }), hospitalPhone: varchar('hospital_phone', { length: 50 }), hospitalSelling: varchar('hospital_selling', { length: 255 }), hospitalWebsite: varchar('hospital_website', { length: 255 }), hospitalNature: int('hospital_nature').notNull().default(-1), doctorName: varchar('doctor_name', { length: 50 }), doctorPhone: varchar('doctor_phone', { length: 50 }), doctorQq: varchar('doctor_qq', { length: 50 }), receptionName: varchar('reception_name', { length: 50 }), receptionPhone: varchar('reception_phone', { length: 50 }), receptionQq: varchar('reception_qq', { length: 50 }), busStation: varchar('bus_station', { length: 100 }), busAddress: varchar('bus_address', { length: 255 }), subwayStation: varchar('subway_station', { length: 100 }), subwayAddress: varchar('subway_address', { length: 255 }), taxiFare: varchar('taxi_fare', { length: 50 }), vipDiscount: varchar('vip_discount', { length: 255 }), returnPoint: varchar('return_point', { length: 50 }), hospitalIntroduction: text('hospital_introduction'), contractPhotos: json('contract_photos'), wechatOpenid: varchar('wechat_openid', { length: 64 }), status: int().notNull().default(1), creatorId: int('creator_id').notNull(), ...timestamps, updaterId: int('updater_id').notNull(), deletedAt: datetime('deleted_at', { mode: 'date' }), version: int().notNull().default(1),
}, (t) => [uniqueIndex('uniq_crm_hospital_account_user').on(t.accountUserId), uniqueIndex('uniq_crm_hospital_name').on(t.hospitalName), index('idx_crm_hospital_region').on(t.provinceId,t.cityId,t.districtId), index('idx_crm_hospital_status').on(t.status), index('idx_crm_hospital_deleted_at').on(t.deletedAt)])

export const crmCustomerStatus = mysqlTable('crm_customer_status', { id: int().primaryKey().autoincrement().notNull(), name: varchar({ length: 50 }).notNull(), sortOrder: int('sort_order').notNull().default(0), status: int().notNull().default(1), ...timestamps }, (t) => [uniqueIndex('uniq_crm_customer_status_name').on(t.name), index('idx_crm_customer_status').on(t.status,t.sortOrder)])
export const crmCustomer = mysqlTable('crm_customer', { id: int().primaryKey().autoincrement().notNull(), numberId: varchar('number_id', { length: 20 }).notNull(), name: varchar({ length: 50 }).notNull(), gender: int().notNull().default(0), birthday: date('birthday', { mode: 'date' }), telphone: varchar({ length: 20 }), mobile: varchar({ length: 20 }), qq: varchar({ length: 20 }), wechat: varchar({ length: 50 }), provinceId: int('province_id'), cityId: int('city_id'), districtId: int('district_id'), address: varchar({ length: 255 }), plastic: varchar({ length: 255 }), statusId: int('status_id').notNull(), remark: text(), ownerUserId: int('owner_user_id').notNull(), creatorId: int('creator_id').notNull(), ...timestamps, updaterId: int('updater_id').notNull(), deletedAt: datetime('deleted_at', { mode: 'date' }), version: int().notNull().default(1) }, (t) => [uniqueIndex('uniq_crm_customer_number_id').on(t.numberId), index('idx_crm_customer_owner').on(t.ownerUserId), index('idx_crm_customer_status').on(t.statusId), index('idx_crm_customer_mobile').on(t.mobile), index('idx_crm_customer_created').on(t.createdAt), index('idx_crm_customer_deleted_at').on(t.deletedAt)])
export const crmCustomerRemark = mysqlTable('crm_customer_remark', { id: int().primaryKey().autoincrement().notNull(), customerId: int('customer_id').notNull(), userId: int('user_id').notNull(), content: text().notNull(), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_customer_remark_customer').on(t.customerId), index('idx_crm_customer_remark_user').on(t.userId)])
export const crmCustomerBrowse = mysqlTable('crm_customer_browse', { id: int().primaryKey().autoincrement().notNull(), customerId: int('customer_id').notNull(), userId: int('user_id').notNull(), action: varchar({ length: 20 }).notNull().default('view'), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_customer_browse_customer').on(t.customerId), index('idx_crm_customer_browse_user').on(t.userId)])
export const crmDispatchStatus = mysqlTable('crm_dispatch_status', { id: int().primaryKey().autoincrement().notNull(), name: varchar({ length: 50 }).notNull(), sortOrder: int('sort_order').notNull().default(0), status: int().notNull().default(1), ...timestamps }, (t) => [uniqueIndex('uniq_crm_dispatch_status_name').on(t.name), index('idx_crm_dispatch_status').on(t.status,t.sortOrder)])
export const crmDispatch = mysqlTable('crm_dispatch', { id: int().primaryKey().autoincrement().notNull(), customerId: int('customer_id').notNull(), hospitalId: int('hospital_id').notNull(), statusId: int('status_id').notNull(), image: varchar({ length: 500 }), receiveQq: varchar('receive_qq', { length: 50 }), receiveWechat: varchar('receive_wechat', { length: 50 }), finishedAt: datetime('finished_at', { mode: 'date' }), creatorId: int('creator_id').notNull(), ...timestamps, updaterId: int('updater_id').notNull(), deletedAt: datetime('deleted_at', { mode: 'date' }), version: int().notNull().default(1) }, (t) => [index('idx_crm_dispatch_customer').on(t.customerId), index('idx_crm_dispatch_hospital').on(t.hospitalId), index('idx_crm_dispatch_status').on(t.statusId), index('idx_crm_dispatch_created').on(t.createdAt), index('idx_crm_dispatch_deleted_at').on(t.deletedAt)])
export const crmDispatchReply = mysqlTable('crm_dispatch_reply', { id: int().primaryKey().autoincrement().notNull(), dispatchId: int('dispatch_id').notNull(), userId: int('user_id').notNull(), content: text().notNull(), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_dispatch_reply_dispatch').on(t.dispatchId), index('idx_crm_dispatch_reply_user').on(t.userId)])
export const crmDispatchFollowLog = mysqlTable('crm_dispatch_follow_log', { id: int().primaryKey().autoincrement().notNull(), dispatchId: int('dispatch_id').notNull(), userId: int('user_id').notNull(), content: text().notNull(), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_dispatch_log_dispatch').on(t.dispatchId), index('idx_crm_dispatch_log_user').on(t.userId)])
export const crmMemberCustomer = mysqlTable('crm_member_customer', { id: int().primaryKey().autoincrement().notNull(), numberId: varchar('number_id', { length: 20 }).notNull(), name: varchar({ length: 50 }).notNull(), gender: int().notNull().default(0), birthday: date('birthday', { mode: 'date' }), address: varchar({ length: 255 }), mobile: varchar({ length: 20 }), project: varchar({ length: 255 }), ownerUserId: int('owner_user_id').notNull(), creatorId: int('creator_id').notNull(), ...timestamps, updaterId: int('updater_id').notNull(), deletedAt: datetime('deleted_at', { mode: 'date' }), version: int().notNull().default(1) }, (t) => [uniqueIndex('uniq_crm_member_number_id').on(t.numberId), index('idx_crm_member_owner').on(t.ownerUserId), index('idx_crm_member_mobile').on(t.mobile), index('idx_crm_member_created').on(t.createdAt), index('idx_crm_member_deleted_at').on(t.deletedAt)])
export const crmMemberRemark = mysqlTable('crm_member_remark', { id: int().primaryKey().autoincrement().notNull(), memberId: int('member_id').notNull(), userId: int('user_id').notNull(), content: text().notNull(), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_member_remark_member').on(t.memberId), index('idx_crm_member_remark_user').on(t.userId)])
export const crmMemberBrowse = mysqlTable('crm_member_browse', { id: int().primaryKey().autoincrement().notNull(), memberId: int('member_id').notNull(), userId: int('user_id').notNull(), action: varchar({ length: 20 }).notNull().default('view'), createdAt: datetime('created_at', { mode: 'date' }).notNull().default(sql`CURRENT_TIMESTAMP(0)`) }, (t) => [index('idx_crm_member_browse_member').on(t.memberId), index('idx_crm_member_browse_user').on(t.userId)])
export const crmHospitalAccount = mysqlTable('crm_hospital_account', { id: int().primaryKey().autoincrement().notNull(), hospitalId: int('hospital_id').notNull(), userId: int('user_id').notNull(), role: varchar({ length: 20 }).notNull().default('member'), status: int().notNull().default(1), remark: varchar({ length: 255 }), creatorId: int('creator_id').notNull(), ...timestamps, updaterId: int('updater_id').notNull(), deletedAt: datetime('deleted_at', { mode: 'date' }) }, (t) => [uniqueIndex('uniq_crm_hospital_account').on(t.hospitalId,t.userId), index('idx_crm_hospital_account_hospital').on(t.hospitalId), index('idx_crm_hospital_account_user').on(t.userId), index('idx_crm_hospital_account_status').on(t.status), index('idx_crm_hospital_account_deleted_at').on(t.deletedAt)])
