import { Type } from '@sinclair/typebox'
export const CrmHospitalSearchQuerySchema = Type.Object({ keyword: Type.Optional(Type.String({ maxLength: 100 })), provinceId: Type.Optional(Type.Integer({ minimum: 1 })), cityId: Type.Optional(Type.Integer({ minimum: 1 })), districtId: Type.Optional(Type.Integer({ minimum: 1 })) }, { $id: 'crmHospitalSearchQuery' })
export const CrmHospitalReqSchema = Type.Object({ accountUserId: Type.Optional(Type.Union([Type.Integer({ minimum: 1 }), Type.Null()])), hospitalName: Type.String({ minLength: 1, maxLength: 100 }), provinceId: Type.Optional(Type.Integer()), cityId: Type.Optional(Type.Integer()), districtId: Type.Optional(Type.Integer()), hospitalAddress: Type.Optional(Type.String({ maxLength: 255 })), hospitalPhone: Type.Optional(Type.String({ maxLength: 50 })), hospitalSelling: Type.Optional(Type.String({ maxLength: 255 })), hospitalWebsite: Type.Optional(Type.String({ maxLength: 255 })), hospitalNature: Type.Optional(Type.Integer()), doctorName: Type.Optional(Type.String({ maxLength: 50 })), doctorPhone: Type.Optional(Type.String({ maxLength: 50 })), doctorQq: Type.Optional(Type.String({ maxLength: 50 })), receptionName: Type.Optional(Type.String({ maxLength: 50 })), receptionPhone: Type.Optional(Type.String({ maxLength: 50 })), receptionQq: Type.Optional(Type.String({ maxLength: 50 })), busStation: Type.Optional(Type.String({ maxLength: 100 })), busAddress: Type.Optional(Type.String({ maxLength: 255 })), subwayStation: Type.Optional(Type.String({ maxLength: 100 })), subwayAddress: Type.Optional(Type.String({ maxLength: 255 })), taxiFare: Type.Optional(Type.String({ maxLength: 50 })), vipDiscount: Type.Optional(Type.String({ maxLength: 255 })), returnPoint: Type.Optional(Type.String({ maxLength: 50 })), hospitalIntroduction: Type.Optional(Type.String({ maxLength: 5000 })), contractPhotos: Type.Optional(Type.Array(Type.String({ maxLength: 500 }))), wechatOpenid: Type.Optional(Type.String({ maxLength: 100 })), status: Type.Optional(Type.Integer({ minimum: 0, maximum: 1 })) }, { $id: 'crmHospitalReq' })
export const CrmHospitalUpdateReqSchema = Type.Partial(CrmHospitalReqSchema, { $id: 'crmHospitalUpdateReq', minProperties: 1 })
export const CrmHospitalAccountCreateReqSchema = Type.Object({ username: Type.String({ minLength: 1, maxLength: 50 }), phone: Type.String({ minLength: 1, maxLength: 20 }), realName: Type.Optional(Type.String({ maxLength: 50 })), email: Type.Optional(Type.String({ maxLength: 100 })), password: Type.String({ minLength: 8, maxLength: 128 }), role: Type.Optional(Type.String({ maxLength: 20, default: 'member' })), remark: Type.Optional(Type.String({ maxLength: 255 })) }, { $id: 'crmHospitalAccountCreateReq' })
export const CrmHospitalAccountAssignReqSchema = Type.Object({ userId: Type.Integer({ minimum: 1 }), role: Type.Optional(Type.String({ maxLength: 20, default: 'member' })), remark: Type.Optional(Type.String({ maxLength: 255 })) }, { $id: 'crmHospitalAccountAssignReq' })
export const CrmHospitalAccountUpdateReqSchema = Type.Object({ role: Type.Optional(Type.String({ maxLength: 20 })), status: Type.Optional(Type.Integer({ minimum: 0, maximum: 1 })), remark: Type.Optional(Type.String({ maxLength: 255 })), username: Type.Optional(Type.String({ minLength: 1, maxLength: 50 })), realName: Type.Optional(Type.String({ maxLength: 50 })), phone: Type.Optional(Type.String({ minLength: 1, maxLength: 20 })), email: Type.Optional(Type.String({ maxLength: 100 })), password: Type.Optional(Type.String({ minLength: 8, maxLength: 128 })) }, { $id: 'crmHospitalAccountUpdateReq', minProperties: 1 })
export type CrmHospitalReq = import('@sinclair/typebox').Static<typeof CrmHospitalReqSchema>
export type CrmHospitalUpdateReq = import('@sinclair/typebox').Static<typeof CrmHospitalUpdateReqSchema>
export type CrmHospitalSearchQuery = import('@sinclair/typebox').Static<typeof CrmHospitalSearchQuerySchema>
export type CrmHospitalAccountCreateReq = import('@sinclair/typebox').Static<typeof CrmHospitalAccountCreateReqSchema>
export type CrmHospitalAccountAssignReq = import('@sinclair/typebox').Static<typeof CrmHospitalAccountAssignReqSchema>
export type CrmHospitalAccountUpdateReq = import('@sinclair/typebox').Static<typeof CrmHospitalAccountUpdateReqSchema>
