import { HospitalsRepository } from '../repositories/hospitals.repository.js'
import { compact, normalizeContractPhotos, HOSPITAL_ACCOUNT_ROLES, assertHospitalAccountRole } from './_shared.js'
import { hashPassword } from '@/utils/password.js'
export class HospitalsService {
 static getById(id:number){return HospitalsRepository.findById(id)}
 static async list(q:any){const p={...q,...requirePage(q)};return {...await HospitalsRepository.list(p),...p}}
 static searchOptions(q:any){return this.list({...q,page:1,pageSize:50})}
 static save(input:any,userId:number,id?:number){const data=compact({accountUserId:input.accountUserId===null?null:input.accountUserId===undefined?undefined:Number(input.accountUserId),hospitalName:input.hospitalName,provinceId:input.provinceId,cityId:input.cityId,districtId:input.districtId,hospitalAddress:input.hospitalAddress,hospitalPhone:input.hospitalPhone,hospitalSelling:input.hospitalSelling,hospitalWebsite:input.hospitalWebsite,hospitalNature:input.hospitalNature,doctorName:input.doctorName,doctorPhone:input.doctorPhone,doctorQq:input.doctorQq,receptionName:input.receptionName,receptionPhone:input.receptionPhone,receptionQq:input.receptionQq,busStation:input.busStation,busAddress:input.busAddress,subwayStation:input.subwayStation,subwayAddress:input.subwayAddress,taxiFare:input.taxiFare,vipDiscount:input.vipDiscount,returnPoint:input.returnPoint,hospitalIntroduction:input.hospitalIntroduction,contractPhotos:normalizeContractPhotos(input.contractPhotos),wechatOpenid:input.wechatOpenid,status:input.status,updaterId:userId});return id?HospitalsRepository.update(id,data):HospitalsRepository.create({...data,creatorId:userId,updaterId:userId})}
 static delete(id:number,userId:number){return HospitalsRepository.update(id,{deletedAt:new Date(),updaterId:userId})}
 static listAccounts(id:number){return HospitalsRepository.listAccounts(id)}
 static async createAccount(id:number,input:any,userId:number){assertHospitalAccountRole(input.role??'member');return HospitalsRepository.createAccount(id,{username:input.username,phone:input.phone,realName:input.realName,email:input.email,passwordHash:await hashPassword(input.password),status:1,creatorId:userId,updaterId:userId},{role:input.role??'member',status:1,remark:input.remark,creatorId:userId,updaterId:userId})}
 static async assignAccount(id:number,input:any,userId:number){assertHospitalAccountRole(input.role??'member');if((await HospitalsRepository.findAccount(id,input.userId))[0])throw new Error('该用户已是医院账号');if(!(await HospitalsRepository.findUser(input.userId))[0])throw new Error('用户不存在');return HospitalsRepository.assignAccount({hospitalId:id,userId:input.userId,role:input.role??'member',status:1,remark:input.remark,creatorId:userId,updaterId:userId})}
 static async updateAccount(id:number,userId:number,input:any,actor:number){const e=(await HospitalsRepository.findAccount(id,userId))[0];if(!e)throw new Error('医院账号关系不存在');if(input.role)assertHospitalAccountRole(input.role);const updates=compact({role:input.role,status:input.status,remark:input.remark,updaterId:actor});if(input.username||input.realName||input.phone||input.email||input.password)await HospitalsRepository.updateUser(userId,compact({username:input.username,realName:input.realName,phone:input.phone,email:input.email,passwordHash:input.password?await hashPassword(input.password):undefined,updaterId:actor}));return HospitalsRepository.updateAccount(e.id,updates)}
 static async deleteAccount(id:number,userId:number,actor:number){const e=(await HospitalsRepository.findAccount(id,userId))[0];if(!e)throw new Error('医院账号关系不存在');if(e.role==='owner'&&Number((await HospitalsRepository.countOwners(id))[0]?.total)<=1)throw new Error('不能解除最后一个负责人');return HospitalsRepository.updateAccount(e.id,{deletedAt:new Date(),updaterId:actor})}
 static bindWechatOpenid(id:number,signature:string,openid:string){const crypto=require('node:crypto');if(crypto.createHash('md5').update(`hospital_bind${id}`).digest('hex')!==signature)throw new Error('微信绑定签名无效');return HospitalsRepository.bindWechatOpenid(id,openid)}
}
function requirePage(q:any){return {page:Math.max(1,Number(q.page??1)),pageSize:Math.max(0,Number(q.pageSize??10))}}
void HOSPITAL_ACCOUNT_ROLES
