import { and, asc, count, desc, eq, gte, lte, like, or, isNull } from 'drizzle-orm'
import { drizzleDb, type AppQueryDb } from '@/db'
import { crmCustomer, crmCustomerStatus, crmCustomerRemark, crmDispatch } from '../db/schema.js'
import { sysUser } from '@/db/schema'
const active=(t:any)=>isNull(t.deletedAt); const page=(q:any,p:any)=>p.pageSize===0?q:q.limit(p.pageSize).offset((p.page-1)*p.pageSize)
export class CustomersRepository {
 static async list(q:any,db:AppQueryDb=drizzleDb){const c:any[]=[active(crmCustomer)];if(q.ownerUserId)c.push(eq(crmCustomer.ownerUserId,q.ownerUserId));if(q.statusId)c.push(eq(crmCustomer.statusId,Number(q.statusId)));if(q.startTime)c.push(gte(crmCustomer.createdAt,new Date(q.startTime)));if(q.endTime)c.push(lte(crmCustomer.createdAt,new Date(q.endTime)));if(q.keyword)c.push(or(like(crmCustomer.mobile,`%${q.keyword}%`),like(crmCustomer.name,`%${q.keyword}%`),like(crmCustomer.numberId,`%${q.keyword}%`))!);const where=and(...c);const [items,totals]=await Promise.all([page(db.select().from(crmCustomer).where(where).orderBy(desc(crmCustomer.createdAt)),q),db.select({total:count()}).from(crmCustomer).where(where)]);return {list:items,total:Number(totals[0]?.total??0)}}
 static async findById(id:number,includeDispatches=false){const [r]=await drizzleDb.select().from(crmCustomer).where(and(eq(crmCustomer.id,id),active(crmCustomer))).limit(1);if(!r)return null;const [status]=await drizzleDb.select().from(crmCustomerStatus).where(eq(crmCustomerStatus.id,r.statusId)).limit(1);const [owner]=await drizzleDb.select({id:sysUser.id,username:sysUser.username,realName:sysUser.realName}).from(sysUser).where(eq(sysUser.id,r.ownerUserId)).limit(1);const dispatches=includeDispatches?await drizzleDb.select().from(crmDispatch).where(eq(crmDispatch.customerId,id)).orderBy(desc(crmDispatch.createdAt)):undefined;return {...r,status:status??null,owner:owner??null,...(includeDispatches?{dispatches}: {})}}
 static async create(input:any,db:AppQueryDb=drizzleDb){const r=await db.insert(crmCustomer).values(input);return this.findById(Number(r[0].insertId))}
 static async update(id:number,input:any,db:AppQueryDb=drizzleDb){await db.update(crmCustomer).set(input).where(eq(crmCustomer.id,id));return this.findById(id)}
 static async nextNumber(){const [r]=await drizzleDb.select({id:crmCustomer.id}).from(crmCustomer).orderBy(desc(crmCustomer.id)).limit(1);return `VIP${String((r?.id??0)+1).padStart(12,'0')}`}
 static addRemark(customerId:number,userId:number,content:string){return drizzleDb.insert(crmCustomerRemark).values({customerId,userId,content})}
 static async ensureDefaultStatuses(db:AppQueryDb=drizzleDb){for(const [id,name] of [[1,'资料录入'],[2,'待跟进'],[3,'重单'],[4,'已手术'],[5,'无效用户']] as const)await db.insert(crmCustomerStatus).values({id,name,sortOrder:id,status:1}).onDuplicateKeyUpdate({set:{name,sortOrder:id,status:1}})}
 static listStatuses(){return drizzleDb.select().from(crmCustomerStatus).where(eq(crmCustomerStatus.status,1)).orderBy(asc(crmCustomerStatus.sortOrder))}
 static async dispatchCustomer(customerId:number,hospitalIds:number[],statusId:number,actorId:number,replyContent:string){const ids=await drizzleDb.transaction(async tx=>{const ids:number[]=[];for(const hospitalId of hospitalIds){const r=await tx.insert(crmDispatch).values({customerId,hospitalId,statusId,finishedAt:new Date(),creatorId:actorId,updaterId:actorId});ids.push(Number(r[0].insertId))}await tx.update(crmCustomer).set({statusId:2,updaterId:actorId}).where(eq(crmCustomer.id,customerId));return ids});return Promise.all(ids.map(id=>this.findById(id)))}
}
